/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.JFrame;
import DAO.OperadorSingleton;
import controller.ControllerCaixa;
import controller.ControllerOperadores;
import controller.ControllerSessao;
import javax.swing.JOptionPane;
import model.Model_Sessao;
import model.Model_Caixa;


/**
 *
 * @author Suporte
 */
public class form_Principal extends javax.swing.JFrame {

    Model_Sessao modelSessao = new Model_Sessao();
    Model_Caixa modelCaixa = new Model_Caixa();
    ControllerSessao controllerSessao = new ControllerSessao();
    ControllerOperadores controllerOperador = new ControllerOperadores();
    ControllerCaixa controllerCaixa = new ControllerCaixa();
    
    public form_Principal() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        this.setDefaultCloseOperation(0);
        //jlOperador.setText(OperadorSingleton.getInstance().getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        JbnPdv = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE VENDAS 2G2M");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_sair.png"))); // NOI18N
        jMenu3.setText("Sair");

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_sair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu3.add(menuSair);

        jMenuBar2.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_cadastros.png"))); // NOI18N
        jMenu4.setText("Cadastros");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_operador.png"))); // NOI18N
        jMenuItem1.setText("Operador");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_aluno (2).png"))); // NOI18N
        jMenuItem2.setText("Aluno");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_produtos.png"))); // NOI18N
        jMenuItem3.setText("Produto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar2.add(jMenu4);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_vendas.png"))); // NOI18N
        jMenu1.setText("Caixa");

        JbnPdv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_pdv.png"))); // NOI18N
        JbnPdv.setText("Abrir Caixa");
        JbnPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbnPdvActionPerformed(evt);
            }
        });
        jMenu1.add(JbnPdv);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_pdv.png"))); // NOI18N
        jMenuItem5.setText("Fechar Caixa");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_forsale.png"))); // NOI18N
        jMenuItem6.setText("PDV");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar2.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_relatorio.png"))); // NOI18N
        jMenu2.setText("Relatorios");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_relatorios.png"))); // NOI18N
        jMenuItem4.setText("Relatorio");
        jMenu2.add(jMenuItem4);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        internal_Operador internalOperador = new internal_Operador();
        
        jDesktopPane1.add(internalOperador);
        internalOperador.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        modelSessao.setFk_id_operador(OperadorSingleton.getInstance().getPk_id_operador());
        modelSessao.setSes_logout_times(Timestamp.valueOf(LocalDateTime.now()));
               
        controllerSessao.updateSessaoController(modelSessao);                
        System.exit(0);       
    }//GEN-LAST:event_menuSairActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        internal_Aluno internalAluno = new internal_Aluno();
        jDesktopPane1.add(internalAluno);
        internalAluno.setVisible(true); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        form_Produto formProduto = new form_Produto();
        jDesktopPane1.add(formProduto);
        formProduto.setVisible(true);       
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void JbnPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbnPdvActionPerformed
      boolean caixaAllowed = controllerOperador.caixaAllowed(OperadorSingleton.getInstance().getPk_id_operador()); 
      if(caixaAllowed){
          internal_AberturaCaixa aberturaCaixa = new internal_AberturaCaixa();
          jDesktopPane1.add(aberturaCaixa);
          aberturaCaixa.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Caixa já aberto");
        }
    }//GEN-LAST:event_JbnPdvActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        modelCaixa.setFk_id_operador(OperadorSingleton.getInstance().getPk_id_operador());
        modelCaixa.setCx_fechamento_times(Timestamp.valueOf(LocalDateTime.now()));
        if(controllerCaixa.updateCaixaController(modelCaixa)){
            JOptionPane.showMessageDialog(this,"Caixa Fechado");
        }else{
            JOptionPane.showMessageDialog(this,"Não existe Caixa Aberto");
        };
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        internal_Perfil formPerfil = new internal_Perfil();
        jDesktopPane1.add(formPerfil);
        formPerfil.setVisible(true);

                
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JbnPdv;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem menuSair;
    // End of variables declaration//GEN-END:variables
}
